name: Provison
on: [push]
jobs:
  exchange:
    runs-on: ubuntu-latest
    steps:
    - name: OIDC
      id: oidc
      run: |
        token=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"\
        "$ACTIONS_ID_TOKEN_REQUEST_URL$audience=sts.amazon.com")
        echo $token
