name: Your Service CLI
on:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  cli:
    uses: github/actions-oidc-debugger@v1
    uses: Yharnix/ci/.github/workflows/main.yml@master
    with:
      plan: auto
