on:
  [push]
jobs:
  auth-and-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: your-org/oidc-auth@v1
        with:
          api-url: 'https://your-api.example.com/prod/ident'
          role: 'data-processing-workflow'

      - name: Run AWS CLI commands
        run: |
          aws sts get-caller-identity
          aws s3 ls
