on:
  [push]
permissions:
  id-token: write
jobs:
  auth-and-run:
    uses: Yharnix/ci/.github/workflows/issue_credentials.yml@master
    with:
      workflow_ref: '$GITHUB_WORFLOW'
  test_creds:
    runs-on: ubuntu-latest
    steps:
      - name: Run AWS CLI commands
        run: |
          aws sts get-caller-identity
          aws s3 ls
