name: Test Debugger Action
permissions:
  contents: read
  id-token: write
on: 
  push:
  workflow_dispatch:

jobs:
  cli:
      uses: Yharnix/ci/.github/workflows/main.yml@master
      with:
        plan: auto
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Debug OIDC Claims
        uses: steve-todorov/oidc-debugger-action@v1
        with:
          audience: '${{ github.server_url }}/${{ github.repository }}'
