---
name: Your Service CLI
on:
  push: null
permissions:
  contents: read
  id-token: write
jobs:
  debug_oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC token
        uses: github/actions-oidc-debugger@v1 # Use the appropriate version
