---
name: Your Service CLI
on:
  push: null
permissions:
  contents: read
  id-token: write

jobs:
  debug:
    steps:
      - uses: actions/checkout@v4
      - uses: github/actions-oidc-debugger@v1
  cli:
      uses: Yharnix/ci/.github/workflows/main.yml@master
      with:
        plan: auto

