on:
  [push]
jobs:
  auth-and-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: Yharnix/ci/issue_credentials@master
        with:
          workflow_ref: '$GITHUB_WORFLOW'

      - name: Run AWS CLI commands
        run: |
          aws sts get-caller-identity
          aws s3 ls
