name: Provison
on: [push]
permissions:
  id-token: write
jobs:
  exchange:
    runs-on: ubuntu-latest
    steps:
    - name: OIDC
      id: oidc
      run: |
        echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        # token=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"\
        # "$ACTIONS_ID_TOKEN_REQUEST_URL$audience=sts.amazon.com")
        # echo $token
